/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo8.senku.UI;
import grupo8.senku.UI.FondoPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicButtonUI;
/**
 *
 * @author brenda
 */

public class FrameJugar extends javax.swing.JFrame {

    /**
     * Creates new form FrameJugar
     */
    private int WIDTH = 1920;
    private int HEIGHT = 1080;
    FondoPanel fondo = new FondoPanel();
    public FrameJugar() {
        this.setContentPane(fondo);
        initComponents();
        personalizarBoton(); // <- ACÁ
        setSize(WIDTH, HEIGHT);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setFont(new java.awt.Font("DejaVu Serif", 3, 70)); // NOI18N
        jButton1.setText("Jugar");
        jButton1.setName("botonJugar"); // NOI18N
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(400, 250));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 430, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalizarBoton() {
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);

        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton1.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(255,204,255));
                g2.fillOval(0, 0, c.getWidth(), c.getHeight());
                g2.dispose();
                super.paint(g, c);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
