/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo8.senku.UI;

import grupo8.senku.controller.ControllerUI;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;

/**
 *
 * @author brenda
 */
public class FrameJugar extends javax.swing.JFrame {
    private final ControllerUI CUIcontrol;
    private final FondoJugar FJfondo;
    /**
     * Creates new form FrameJugar2
     * @param control
     */
    public FrameJugar(ControllerUI control) {
        this.CUIcontrol = control;
        FJfondo = new FondoJugar();
        this.setContentPane(FJfondo);
        initComponents();
        vpersonalizarBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Efectos = new javax.swing.JToggleButton();
        Musica = new javax.swing.JToggleButton();
        exit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("DejaVu Serif", 2, 70)); // NOI18N
        jButton1.setText("jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Efectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audio.png"))); // NOI18N
        Efectos.setSelected(true);
        Efectos.setBorderPainted(false);
        Efectos.setContentAreaFilled(false);
        Efectos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Efectos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Efectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectosActionPerformed(evt);
            }
        });

        Musica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musica.png"))); // NOI18N
        Musica.setBorderPainted(false);
        Musica.setContentAreaFilled(false);
        Musica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Musica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicaActionPerformed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 465, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 465, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(exit)
                .addGap(18, 18, 18)
                .addComponent(Efectos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Musica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Efectos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Musica, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(243, 243, 243)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CUIcontrol.vjugar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EfectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectosActionPerformed
        CUIcontrol.vcontrolarEfectoSonido();
    }//GEN-LAST:event_EfectosActionPerformed

    private void MusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicaActionPerformed
        CUIcontrol.vcontrolarMusica();
    }//GEN-LAST:event_MusicaActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        CUIcontrol.vSalirJuego();
    }//GEN-LAST:event_exitActionPerformed
   
    private void vpersonalizarBoton() {
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);

        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton1.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(new Color(106, 65, 60));
                g2.fillOval(0, 0, c.getWidth(), c.getHeight());
                g2.dispose();
                super.paint(g, c);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Efectos;
    private javax.swing.JToggleButton Musica;
    private javax.swing.JToggleButton exit;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
