/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo8.senku.UI;

import grupo8.senku.controller.ControllerUI;

/**
 *
 * @author Azurduy
 */
public class SeleccionNiveles extends javax.swing.JFrame {
    private ControllerUI control;
    /**
     * Creates new form SeleccionNiveles
     */
    public SeleccionNiveles(ControllerUI control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionNiveles = new javax.swing.JPanel();
        nivelDos = new javax.swing.JButton();
        nivelUno = new javax.swing.JButton();
        nivelTres = new javax.swing.JButton();
        botonesNiveles = new javax.swing.JToolBar();
        atras = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionNiveles.setBackground(new java.awt.Color(180, 132, 108));

        nivelDos.setBackground(new java.awt.Color(125, 90, 80));
        nivelDos.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        nivelDos.setText("2");
        nivelDos.setBorderPainted(false);

        nivelUno.setBackground(new java.awt.Color(125, 90, 80));
        nivelUno.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        nivelUno.setText("1");
        nivelUno.setBorderPainted(false);
        nivelUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelUnoActionPerformed(evt);
            }
        });

        nivelTres.setBackground(new java.awt.Color(125, 90, 80));
        nivelTres.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        nivelTres.setText("3");
        nivelTres.setBorderPainted(false);

        botonesNiveles.setRollover(true);
        botonesNiveles.setOpaque(false);

        atras.setBackground(new java.awt.Color(180, 132, 108));
        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atras.png"))); // NOI18N
        atras.setBorderPainted(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        botonesNiveles.add(atras);

        menu.setBackground(new java.awt.Color(180, 132, 108));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        botonesNiveles.add(menu);

        javax.swing.GroupLayout seleccionNivelesLayout = new javax.swing.GroupLayout(seleccionNiveles);
        seleccionNiveles.setLayout(seleccionNivelesLayout);
        seleccionNivelesLayout.setHorizontalGroup(
            seleccionNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccionNivelesLayout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(nivelUno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nivelDos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nivelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(seleccionNivelesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonesNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seleccionNivelesLayout.setVerticalGroup(
            seleccionNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccionNivelesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonesNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(seleccionNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivelUno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelDos, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nivelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(seleccionNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(seleccionNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivelUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelUnoActionPerformed
        control.iniciarJuego();
    }//GEN-LAST:event_nivelUnoActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        control.irHome();
    }//GEN-LAST:event_menuActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        control.regresarPantalla();
    }//GEN-LAST:event_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JToolBar botonesNiveles;
    private javax.swing.JButton menu;
    private javax.swing.JButton nivelDos;
    private javax.swing.JButton nivelTres;
    private javax.swing.JButton nivelUno;
    private javax.swing.JPanel seleccionNiveles;
    // End of variables declaration//GEN-END:variables
}
