/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo8.senku.UI;
import grupo8.senku.controller.ControllerUI;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Azurduy
 */
public class Seleccionjuego extends javax.swing.JFrame {
    private ControllerUI control;
    /**
     * Creates new form Seleccionjuego
     */
    public Seleccionjuego(ControllerUI control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionJuego = new javax.swing.JPanel();
        contenedorTriangulo = new javax.swing.JPanel();
        opcionTriangulo = new javax.swing.JButton();
        dificultadTriangulo = new javax.swing.JLabel();
        contenedorCruz = new javax.swing.JPanel();
        opcionCruz = new javax.swing.JButton();
        dificultadCruz = new javax.swing.JLabel();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionJuego.setBackground(new java.awt.Color(180, 132, 108));

        contenedorTriangulo.setBackground(new java.awt.Color(125, 90, 80));

        opcionTriangulo.setBackground(new java.awt.Color(125, 90, 80));
        opcionTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/triangulo.png"))); // NOI18N
        opcionTriangulo.setBorderPainted(false);
        opcionTriangulo.setRolloverEnabled(false);
        opcionTriangulo.setVerifyInputWhenFocusTarget(false);
        opcionTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionTrianguloActionPerformed(evt);
            }
        });

        dificultadTriangulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dificultadTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dificultadTriangulo.setText("DIFICULTAD FACIL");

        javax.swing.GroupLayout contenedorTrianguloLayout = new javax.swing.GroupLayout(contenedorTriangulo);
        contenedorTriangulo.setLayout(contenedorTrianguloLayout);
        contenedorTrianguloLayout.setHorizontalGroup(
            contenedorTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorTrianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dificultadTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorTrianguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opcionTriangulo)
                .addGap(77, 77, 77))
        );
        contenedorTrianguloLayout.setVerticalGroup(
            contenedorTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorTrianguloLayout.createSequentialGroup()
                .addComponent(opcionTriangulo)
                .addGap(18, 18, 18)
                .addComponent(dificultadTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        contenedorCruz.setBackground(new java.awt.Color(125, 90, 80));

        opcionCruz.setBackground(new java.awt.Color(125, 90, 80));
        opcionCruz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cruz.png"))); // NOI18N
        opcionCruz.setBorderPainted(false);
        opcionCruz.setRolloverEnabled(false);
        opcionCruz.setVerifyInputWhenFocusTarget(false);

        dificultadCruz.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dificultadCruz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dificultadCruz.setText("DIFICULTAD DIFICIL");

        javax.swing.GroupLayout contenedorCruzLayout = new javax.swing.GroupLayout(contenedorCruz);
        contenedorCruz.setLayout(contenedorCruzLayout);
        contenedorCruzLayout.setHorizontalGroup(
            contenedorCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorCruzLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dificultadCruz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contenedorCruzLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(opcionCruz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedorCruzLayout.setVerticalGroup(
            contenedorCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorCruzLayout.createSequentialGroup()
                .addComponent(opcionCruz)
                .addGap(18, 18, 18)
                .addComponent(dificultadCruz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        menu.setBackground(new java.awt.Color(180, 132, 108));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccionJuegoLayout = new javax.swing.GroupLayout(seleccionJuego);
        seleccionJuego.setLayout(seleccionJuegoLayout);
        seleccionJuegoLayout.setHorizontalGroup(
            seleccionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionJuegoLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(seleccionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu)
                    .addGroup(seleccionJuegoLayout.createSequentialGroup()
                        .addComponent(contenedorTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contenedorCruz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        seleccionJuegoLayout.setVerticalGroup(
            seleccionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionJuegoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menu)
                .addGap(41, 41, 41)
                .addGroup(seleccionJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contenedorCruz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(530, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seleccionJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 543, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        control.irHome();
    }//GEN-LAST:event_menuActionPerformed

    private void opcionTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionTrianguloActionPerformed
        control.seleccionarFacil();
    }//GEN-LAST:event_opcionTrianguloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorCruz;
    private javax.swing.JPanel contenedorTriangulo;
    private javax.swing.JLabel dificultadCruz;
    private javax.swing.JLabel dificultadTriangulo;
    private javax.swing.JButton menu;
    private javax.swing.JButton opcionCruz;
    private javax.swing.JButton opcionTriangulo;
    private javax.swing.JPanel seleccionJuego;
    // End of variables declaration//GEN-END:variables
}
