/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo8.senku.UI;

import grupo8.senku.controller.ControllerUI;

/**
 *
 * @author Azurduy
 */
public class SeleccionNiveles extends javax.swing.JFrame {
    private final ControllerUI CUIcontrol;
    private final FondoApp FAfondo;
    /**
     * Creates new form SeleccionNiveles
     * @param CUIcontrol
     */
    public SeleccionNiveles(ControllerUI CUIcontrol) {
        this.CUIcontrol = CUIcontrol;
        FAfondo = new FondoApp();
        this.setContentPane(FAfondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionNiveles = new javax.swing.JPanel();
        nivelUno = new javax.swing.JButton();
        botonesNiveles = new javax.swing.JToolBar();
        atras = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionNiveles.setBackground(new java.awt.Color(180, 132, 108));
        seleccionNiveles.setOpaque(false);

        nivelUno.setBackground(new java.awt.Color(106, 65, 60));
        nivelUno.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        nivelUno.setText("1");
        nivelUno.setBorderPainted(false);
        nivelUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelUnoActionPerformed(evt);
            }
        });

        botonesNiveles.setBackground(new java.awt.Color(215, 161, 117));
        botonesNiveles.setFloatable(true);
        botonesNiveles.setForeground(new java.awt.Color(215, 161, 117));
        botonesNiveles.setRollover(true);
        botonesNiveles.setBorderPainted(false);
        botonesNiveles.setOpaque(false);

        atras.setBackground(new java.awt.Color(215, 161, 117));
        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atras.png"))); // NOI18N
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        botonesNiveles.add(atras);

        menu.setBackground(new java.awt.Color(215, 161, 117));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        botonesNiveles.add(menu);

        javax.swing.GroupLayout seleccionNivelesLayout = new javax.swing.GroupLayout(seleccionNiveles);
        seleccionNiveles.setLayout(seleccionNivelesLayout);
        seleccionNivelesLayout.setHorizontalGroup(
            seleccionNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionNivelesLayout.createSequentialGroup()
                .addGroup(seleccionNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonesNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(seleccionNivelesLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(nivelUno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(547, Short.MAX_VALUE))
        );
        seleccionNivelesLayout.setVerticalGroup(
            seleccionNivelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seleccionNivelesLayout.createSequentialGroup()
                .addComponent(botonesNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(nivelUno, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(seleccionNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(seleccionNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivelUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelUnoActionPerformed
        CUIcontrol.viniciarJuego();
    }//GEN-LAST:event_nivelUnoActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        CUIcontrol.virHome();
    }//GEN-LAST:event_menuActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        CUIcontrol.vregresarPantalla();
    }//GEN-LAST:event_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JToolBar botonesNiveles;
    private javax.swing.JButton menu;
    private javax.swing.JButton nivelUno;
    private javax.swing.JPanel seleccionNiveles;
    // End of variables declaration//GEN-END:variables
}
