/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package grupo8.senku.UI;

import grupo8.senku.controller.ControllerUI;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.Border;

/**
 *
 * @author INTEL
 */



//Subclase por defecto ---------------------------------------------------------
public class VentanaJuego extends javax.swing.JFrame {
    private FondoPanel fondo = new FondoPanel();
    private ControllerUI control;
    /** Creates new form Tablero
     * @param control */
    public VentanaJuego(ControllerUI control) {
        this.control = control;
        this.setContentPane(fondo);
        initComponents();
    }
    
    public void vAgregarBotonesTablero(JButton boton, int est){
        Color CcolorBorde = new Color(0xcca46d);
        Border Bborde = BorderFactory.createLineBorder(CcolorBorde,3);
        if(est > 0){
            boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fichaActiva.png")));
            boton.setBorder(Bborde);
        }else if(est == 0){
            boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ficha.png")));
            boton.setBorder(Bborde);
        }else{
            boton.setEnabled(false);           
            boton.setOpaque(false);            
            boton.setFocusPainted(false);
            boton.setBorderPainted(false);
        }
        boton.setContentAreaFilled(false);
        boton.setText("");
        boton.setPreferredSize(new Dimension(50,50));
        tablero.add(boton);
    }
    
    public void vIniciarBotones(int fil, int col){
        tablero.setLayout(new java.awt.GridLayout(fil, col));
    }
    
    public void setCronometro(int itiempo){
        cronometro.setText(itiempo/60 + " " + ":" + itiempo%60 + " ");
    }
    
    
//-------------------------------------------------------------------------------------------------------
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaJuego = new FondoPanel();
        tablero = new javax.swing.JPanel();
        pista = new javax.swing.JButton();
        cronometro = new javax.swing.JLabel();
        botonesTablero = new javax.swing.JToolBar();
        restart = new javax.swing.JButton();
        pausa = new javax.swing.JButton();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventanaJuego.setBackground(new java.awt.Color(180, 132, 108));
        ventanaJuego.setPreferredSize(new java.awt.Dimension(1385, 671));

        tablero.setBackground(new java.awt.Color(125, 90, 80));
        tablero.setPreferredSize(new java.awt.Dimension(400, 400));
        tablero.setLayout(new java.awt.GridLayout(7, 7));

        pista.setBackground(new java.awt.Color(180, 132, 108));
        pista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pista.png"))); // NOI18N
        pista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistaActionPerformed(evt);
            }
        });

        cronometro.setBackground(new java.awt.Color(125, 90, 80));
        cronometro.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        cronometro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cronometro.setText("Cronometro");
        cronometro.setAlignmentY(0.0F);
        cronometro.setOpaque(true);

        botonesTablero.setBackground(cronometro.getBackground());
        botonesTablero.setRollover(true);
        botonesTablero.setBorderPainted(false);
        botonesTablero.setOpaque(false);

        restart.setBackground(new java.awt.Color(180, 132, 108));
        restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restart.png"))); // NOI18N
        restart.setFocusable(false);
        restart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        restart.setOpaque(true);
        restart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });
        botonesTablero.add(restart);
        restart.getAccessibleContext().setAccessibleDescription("");

        pausa.setBackground(new java.awt.Color(180, 132, 108));
        pausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pausa.png"))); // NOI18N
        pausa.setOpaque(true);
        pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaActionPerformed(evt);
            }
        });
        botonesTablero.add(pausa);

        menu.setBackground(new java.awt.Color(180, 132, 108));
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casa.png"))); // NOI18N
        menu.setOpaque(true);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        botonesTablero.add(menu);

        javax.swing.GroupLayout ventanaJuegoLayout = new javax.swing.GroupLayout(ventanaJuego);
        ventanaJuego.setLayout(ventanaJuegoLayout);
        ventanaJuegoLayout.setHorizontalGroup(
            ventanaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaJuegoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonesTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaJuegoLayout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        ventanaJuegoLayout.setVerticalGroup(
            ventanaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaJuegoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ventanaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pista)
                    .addComponent(botonesTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ventanaJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventanaJuegoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(ventanaJuegoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        control.irHome();
    }//GEN-LAST:event_menuActionPerformed

    private void pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaActionPerformed
        control.vusarCronometro();
    }//GEN-LAST:event_pausaActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        
    }//GEN-LAST:event_restartActionPerformed

    private void pistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pistaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar botonesTablero;
    private javax.swing.JLabel cronometro;
    private javax.swing.JButton menu;
    private javax.swing.JButton pausa;
    private javax.swing.JButton pista;
    private javax.swing.JButton restart;
    private javax.swing.JPanel tablero;
    private javax.swing.JPanel ventanaJuego;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
    
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/tablero.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
}
