/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package grupo8.senku.UI;

import grupo8.senku.UI.*;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author INTEL
 */



//Subclase por defecto ---------------------------------------------------------
public class VentanaJuego extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();

    /** Creates new form Tablero */
    public VentanaJuego() {
        this.setContentPane(fondo);
        
        initComponents();
    }
    
    
    
//-------------------------------------------------------------------------------------------------------
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new FondoPanel();
        Tablero = new javax.swing.JPanel();
        Ficha1 = new javax.swing.JButton();
        Ficha2 = new javax.swing.JButton();
        Ficha3 = new javax.swing.JButton();
        Ficha4 = new javax.swing.JButton();
        Ficha5 = new javax.swing.JButton();
        Ficha6 = new javax.swing.JButton();
        Ficha9 = new javax.swing.JButton();
        Ficha10 = new javax.swing.JButton();
        Ficha11 = new javax.swing.JButton();
        Ficha12 = new javax.swing.JButton();
        Ficha13 = new javax.swing.JButton();
        Ficha7 = new javax.swing.JButton();
        Ficha8 = new javax.swing.JButton();
        Ficha14 = new javax.swing.JButton();
        Ficha15 = new javax.swing.JButton();
        Ficha16 = new javax.swing.JButton();
        Ficha17 = new javax.swing.JButton();
        Ficha18 = new javax.swing.JButton();
        Ficha19 = new javax.swing.JButton();
        Ficha20 = new javax.swing.JButton();
        Ficha21 = new javax.swing.JButton();
        Ficha22 = new javax.swing.JButton();
        Ficha23 = new javax.swing.JButton();
        Ficha24 = new javax.swing.JButton();
        Ficha25 = new javax.swing.JButton();
        Ficha26 = new javax.swing.JButton();
        Ficha27 = new javax.swing.JButton();
        Ficha28 = new javax.swing.JButton();
        Ficha29 = new javax.swing.JButton();
        Ficha30 = new javax.swing.JButton();
        Ficha31 = new javax.swing.JButton();
        Ficha32 = new javax.swing.JButton();
        Ficha33 = new javax.swing.JButton();
        Ficha34 = new javax.swing.JButton();
        Ficha35 = new javax.swing.JButton();
        Ficha36 = new javax.swing.JButton();
        Ficha37 = new javax.swing.JButton();
        Ficha38 = new javax.swing.JButton();
        Ficha39 = new javax.swing.JButton();
        Ficha40 = new javax.swing.JButton();
        Ficha41 = new javax.swing.JButton();
        Ficha42 = new javax.swing.JButton();
        Ficha43 = new javax.swing.JButton();
        Ficha44 = new javax.swing.JButton();
        Ficha45 = new javax.swing.JButton();
        Ficha46 = new javax.swing.JButton();
        Ficha47 = new javax.swing.JButton();
        Ficha48 = new javax.swing.JButton();
        Ficha49 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(159, 133, 116));
        Fondo.setPreferredSize(new java.awt.Dimension(1947, 1423));

        Tablero.setBackground(new java.awt.Color(135, 105, 85));
        Tablero.setLayout(new java.awt.GridLayout(7, 7));

        Ficha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha1.setBorderPainted(false);
        Ficha1.setContentAreaFilled(false);
        Ficha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha1ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha1);

        Ficha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha2.setBorderPainted(false);
        Ficha2.setContentAreaFilled(false);
        Ficha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha2ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha2);

        Ficha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha3.setBorderPainted(false);
        Ficha3.setContentAreaFilled(false);
        Ficha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha3ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha3);

        Ficha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha4.setBorderPainted(false);
        Ficha4.setContentAreaFilled(false);
        Ficha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha4ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha4);

        Ficha5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha5.setBorderPainted(false);
        Ficha5.setContentAreaFilled(false);
        Ficha5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha5ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha5);

        Ficha6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha6.setBorderPainted(false);
        Ficha6.setContentAreaFilled(false);
        Ficha6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha6ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha6);

        Ficha9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha9.setBorderPainted(false);
        Ficha9.setContentAreaFilled(false);
        Ficha9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha9ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha9);

        Ficha10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha10.setBorderPainted(false);
        Ficha10.setContentAreaFilled(false);
        Ficha10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha10ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha10);

        Ficha11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha11.setBorderPainted(false);
        Ficha11.setContentAreaFilled(false);
        Ficha11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha11ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha11);

        Ficha12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha12.setBorderPainted(false);
        Ficha12.setContentAreaFilled(false);
        Ficha12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha12ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha12);

        Ficha13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha13.setBorderPainted(false);
        Ficha13.setContentAreaFilled(false);
        Ficha13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha13ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha13);

        Ficha7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha7.setBorderPainted(false);
        Ficha7.setContentAreaFilled(false);
        Ficha7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha7ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha7);

        Ficha8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha8.setBorderPainted(false);
        Ficha8.setContentAreaFilled(false);
        Ficha8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha8ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha8);

        Ficha14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha14.setBorderPainted(false);
        Ficha14.setContentAreaFilled(false);
        Ficha14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha14ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha14);

        Ficha15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha15.setBorderPainted(false);
        Ficha15.setContentAreaFilled(false);
        Ficha15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha15ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha15);

        Ficha16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha16.setBorderPainted(false);
        Ficha16.setContentAreaFilled(false);
        Ficha16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha16ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha16);

        Ficha17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha17.setBorderPainted(false);
        Ficha17.setContentAreaFilled(false);
        Ficha17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha17ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha17);

        Ficha18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha18.setBorderPainted(false);
        Ficha18.setContentAreaFilled(false);
        Ficha18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha18ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha18);

        Ficha19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha19.setBorderPainted(false);
        Ficha19.setContentAreaFilled(false);
        Ficha19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha19ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha19);

        Ficha20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha20.setBorderPainted(false);
        Ficha20.setContentAreaFilled(false);
        Ficha20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha20ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha20);

        Ficha21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha21.setBorderPainted(false);
        Ficha21.setContentAreaFilled(false);
        Ficha21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha21ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha21);

        Ficha22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha22.setBorderPainted(false);
        Ficha22.setContentAreaFilled(false);
        Ficha22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha22ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha22);

        Ficha23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha23.setBorderPainted(false);
        Ficha23.setContentAreaFilled(false);
        Ficha23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha23ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha23);

        Ficha24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha24.setBorderPainted(false);
        Ficha24.setContentAreaFilled(false);
        Ficha24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha24ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha24);

        Ficha25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha25.setBorderPainted(false);
        Ficha25.setContentAreaFilled(false);
        Ficha25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha25ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha25);

        Ficha26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha26.setBorderPainted(false);
        Ficha26.setContentAreaFilled(false);
        Ficha26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha26ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha26);

        Ficha27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha27.setBorderPainted(false);
        Ficha27.setContentAreaFilled(false);
        Ficha27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha27ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha27);

        Ficha28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha28.setBorderPainted(false);
        Ficha28.setContentAreaFilled(false);
        Ficha28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha28ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha28);

        Ficha29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha29.setBorderPainted(false);
        Ficha29.setContentAreaFilled(false);
        Ficha29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha29ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha29);

        Ficha30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha30.setBorderPainted(false);
        Ficha30.setContentAreaFilled(false);
        Ficha30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha30ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha30);

        Ficha31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha31.setBorderPainted(false);
        Ficha31.setContentAreaFilled(false);
        Ficha31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha31ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha31);

        Ficha32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha32.setBorderPainted(false);
        Ficha32.setContentAreaFilled(false);
        Ficha32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha32ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha32);

        Ficha33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha33.setBorderPainted(false);
        Ficha33.setContentAreaFilled(false);
        Ficha33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha33ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha33);

        Ficha34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha34.setBorderPainted(false);
        Ficha34.setContentAreaFilled(false);
        Ficha34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha34ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha34);

        Ficha35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha35.setBorderPainted(false);
        Ficha35.setContentAreaFilled(false);
        Ficha35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha35ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha35);

        Ficha36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha36.setBorderPainted(false);
        Ficha36.setContentAreaFilled(false);
        Ficha36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha36ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha36);

        Ficha37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha37.setBorderPainted(false);
        Ficha37.setContentAreaFilled(false);
        Ficha37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha37ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha37);

        Ficha38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha38.setBorderPainted(false);
        Ficha38.setContentAreaFilled(false);
        Ficha38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha38ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha38);

        Ficha39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha39.setBorderPainted(false);
        Ficha39.setContentAreaFilled(false);
        Ficha39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha39ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha39);

        Ficha40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha40.setBorderPainted(false);
        Ficha40.setContentAreaFilled(false);
        Ficha40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha40ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha40);

        Ficha41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha41.setBorderPainted(false);
        Ficha41.setContentAreaFilled(false);
        Ficha41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha41ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha41);

        Ficha42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha42.setBorderPainted(false);
        Ficha42.setContentAreaFilled(false);
        Ficha42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha42ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha42);

        Ficha43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha43.setBorderPainted(false);
        Ficha43.setContentAreaFilled(false);
        Ficha43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha43ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha43);

        Ficha44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha44.setBorderPainted(false);
        Ficha44.setContentAreaFilled(false);
        Ficha44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha44ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha44);

        Ficha45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha45.setBorderPainted(false);
        Ficha45.setContentAreaFilled(false);
        Ficha45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha45ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha45);

        Ficha46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha46.setBorderPainted(false);
        Ficha46.setContentAreaFilled(false);
        Ficha46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha46ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha46);

        Ficha47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha47.setBorderPainted(false);
        Ficha47.setContentAreaFilled(false);
        Ficha47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha47ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha47);

        Ficha48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha48.setBorderPainted(false);
        Ficha48.setContentAreaFilled(false);
        Ficha48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha48ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha48);

        Ficha49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grupo8/senku/UI/resources/ficha.png"))); // NOI18N
        Ficha49.setBorderPainted(false);
        Ficha49.setContentAreaFilled(false);
        Ficha49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ficha49ActionPerformed(evt);
            }
        });
        Tablero.add(Ficha49);

        jButton5.setBackground(new java.awt.Color(159, 133, 116));
        jButton5.setText("Pista");

        jLabel1.setText("Temporizador");

        jToolBar1.setBackground(new java.awt.Color(159, 133, 116));
        jToolBar1.setRollover(true);

        jButton2.setBackground(new java.awt.Color(159, 133, 116));
        jButton2.setText("ReStart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(159, 133, 116));
        jButton3.setText("Pausa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(159, 133, 116));
        jButton4.setText("Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(655, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1532, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton5))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118)
                .addComponent(Tablero, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(452, 452, 452))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Ficha49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha49ActionPerformed

    private void Ficha48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha48ActionPerformed

    private void Ficha47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha47ActionPerformed

    private void Ficha46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha46ActionPerformed

    private void Ficha45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha45ActionPerformed

    private void Ficha44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha44ActionPerformed

    private void Ficha43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha43ActionPerformed

    private void Ficha42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha42ActionPerformed

    private void Ficha41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha41ActionPerformed

    private void Ficha40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha40ActionPerformed

    private void Ficha39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha39ActionPerformed

    private void Ficha38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha38ActionPerformed

    private void Ficha37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha37ActionPerformed

    private void Ficha36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha36ActionPerformed

    private void Ficha35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha35ActionPerformed

    private void Ficha34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha34ActionPerformed

    private void Ficha33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha33ActionPerformed

    private void Ficha32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha32ActionPerformed

    private void Ficha31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha31ActionPerformed

    private void Ficha30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha30ActionPerformed

    private void Ficha29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha29ActionPerformed

    private void Ficha28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha28ActionPerformed

    private void Ficha27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha27ActionPerformed

    private void Ficha26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha26ActionPerformed

    private void Ficha25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha25ActionPerformed

    private void Ficha24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha24ActionPerformed

    private void Ficha23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha23ActionPerformed

    private void Ficha22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha22ActionPerformed

    private void Ficha21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha21ActionPerformed

    private void Ficha20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha20ActionPerformed

    private void Ficha19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha19ActionPerformed

    private void Ficha18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha18ActionPerformed

    private void Ficha17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha17ActionPerformed

    private void Ficha16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha16ActionPerformed

    private void Ficha15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha15ActionPerformed

    private void Ficha14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha14ActionPerformed

    private void Ficha8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha8ActionPerformed

    private void Ficha7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha7ActionPerformed

    private void Ficha13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha13ActionPerformed

    private void Ficha12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha12ActionPerformed

    private void Ficha11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha11ActionPerformed

    private void Ficha10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha10ActionPerformed

    private void Ficha9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha9ActionPerformed

    private void Ficha6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha6ActionPerformed

    private void Ficha5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha5ActionPerformed

    private void Ficha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha4ActionPerformed

    private void Ficha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha3ActionPerformed

    private void Ficha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha2ActionPerformed

    private void Ficha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ficha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ficha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ficha1;
    private javax.swing.JButton Ficha10;
    private javax.swing.JButton Ficha11;
    private javax.swing.JButton Ficha12;
    private javax.swing.JButton Ficha13;
    private javax.swing.JButton Ficha14;
    private javax.swing.JButton Ficha15;
    private javax.swing.JButton Ficha16;
    private javax.swing.JButton Ficha17;
    private javax.swing.JButton Ficha18;
    private javax.swing.JButton Ficha19;
    private javax.swing.JButton Ficha2;
    private javax.swing.JButton Ficha20;
    private javax.swing.JButton Ficha21;
    private javax.swing.JButton Ficha22;
    private javax.swing.JButton Ficha23;
    private javax.swing.JButton Ficha24;
    private javax.swing.JButton Ficha25;
    private javax.swing.JButton Ficha26;
    private javax.swing.JButton Ficha27;
    private javax.swing.JButton Ficha28;
    private javax.swing.JButton Ficha29;
    private javax.swing.JButton Ficha3;
    private javax.swing.JButton Ficha30;
    private javax.swing.JButton Ficha31;
    private javax.swing.JButton Ficha32;
    private javax.swing.JButton Ficha33;
    private javax.swing.JButton Ficha34;
    private javax.swing.JButton Ficha35;
    private javax.swing.JButton Ficha36;
    private javax.swing.JButton Ficha37;
    private javax.swing.JButton Ficha38;
    private javax.swing.JButton Ficha39;
    private javax.swing.JButton Ficha4;
    private javax.swing.JButton Ficha40;
    private javax.swing.JButton Ficha41;
    private javax.swing.JButton Ficha42;
    private javax.swing.JButton Ficha43;
    private javax.swing.JButton Ficha44;
    private javax.swing.JButton Ficha45;
    private javax.swing.JButton Ficha46;
    private javax.swing.JButton Ficha47;
    private javax.swing.JButton Ficha48;
    private javax.swing.JButton Ficha49;
    private javax.swing.JButton Ficha5;
    private javax.swing.JButton Ficha6;
    private javax.swing.JButton Ficha7;
    private javax.swing.JButton Ficha8;
    private javax.swing.JButton Ficha9;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Tablero;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        private Image imagen;
    
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/resources/tablero.jpeg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);
            super.paint(g);
        }
    }
}
